using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Common.Dynamic;

namespace Apps.Ahrefs.Handlers.Static;

public class CountryCodeStaticHandler : IStaticDataSourceItemHandler
{
    public IEnumerable<DataSourceItem> GetData()
    {
        return new List<DataSourceItem>
        {
            new DataSourceItem("ad", "Andorra"),
            new DataSourceItem("ae", "United Arab Emirates"),
            new DataSourceItem("af", "Afghanistan"),
            new DataSourceItem("ag", "Antigua and Barbuda"),
            new DataSourceItem("ai", "Anguilla"),
            new DataSourceItem("al", "Albania"),
            new DataSourceItem("am", "Armenia"),
            new DataSourceItem("ao", "Angola"),
            new DataSourceItem("ar", "Argentina"),
            new DataSourceItem("as", "American Samoa"),
            new DataSourceItem("at", "Austria"),
            new DataSourceItem("au", "Australia"),
            new DataSourceItem("aw", "Aruba"),
            new DataSourceItem("az", "Azerbaijan"),
            new DataSourceItem("ba", "Bosnia and Herzegovina"),
            new DataSourceItem("bb", "Barbados"),
            new DataSourceItem("bd", "Bangladesh"),
            new DataSourceItem("be", "Belgium"),
            new DataSourceItem("bf", "Burkina Faso"),
            new DataSourceItem("bg", "Bulgaria"),
            new DataSourceItem("bh", "Bahrain"),
            new DataSourceItem("bi", "Burundi"),
            new DataSourceItem("bj", "Benin"),
            new DataSourceItem("bn", "Brunei Darussalam"),
            new DataSourceItem("bo", "Bolivia"),
            new DataSourceItem("br", "Brazil"),
            new DataSourceItem("bs", "Bahamas"),
            new DataSourceItem("bt", "Bhutan"),
            new DataSourceItem("bw", "Botswana"),
            new DataSourceItem("by", "Belarus"),
            new DataSourceItem("bz", "Belize"),
            new DataSourceItem("ca", "Canada"),
            new DataSourceItem("cd", "Congo, Democratic Republic"),
            new DataSourceItem("cf", "Central African Republic"),
            new DataSourceItem("cg", "Congo"),
            new DataSourceItem("ch", "Switzerland"),
            new DataSourceItem("ci", "Côte d’Ivoire"),
            new DataSourceItem("ck", "Cook Islands"),
            new DataSourceItem("cl", "Chile"),
            new DataSourceItem("cm", "Cameroon"),
            new DataSourceItem("cn", "China"),
            new DataSourceItem("co", "Colombia"),
            new DataSourceItem("cr", "Costa Rica"),
            new DataSourceItem("cu", "Cuba"),
            new DataSourceItem("cv", "Cabo Verde"),
            new DataSourceItem("cy", "Cyprus"),
            new DataSourceItem("cz", "Czechia"),
            new DataSourceItem("de", "Germany"),
            new DataSourceItem("dj", "Djibouti"),
            new DataSourceItem("dk", "Denmark"),
            new DataSourceItem("dm", "Dominica"),
            new DataSourceItem("do", "Dominican Republic"),
            new DataSourceItem("dz", "Algeria"),
            new DataSourceItem("ec", "Ecuador"),
            new DataSourceItem("ee", "Estonia"),
            new DataSourceItem("eg", "Egypt"),
            new DataSourceItem("es", "Spain"),
            new DataSourceItem("et", "Ethiopia"),
            new DataSourceItem("fi", "Finland"),
            new DataSourceItem("fj", "Fiji"),
            new DataSourceItem("fm", "Micronesia"),
            new DataSourceItem("fo", "Faroe Islands"),
            new DataSourceItem("fr", "France"),
            new DataSourceItem("ga", "Gabon"),
            new DataSourceItem("gb", "United Kingdom"),
            new DataSourceItem("gd", "Grenada"),
            new DataSourceItem("ge", "Georgia"),
            new DataSourceItem("gf", "French Guiana"),
            new DataSourceItem("gg", "Guernsey"),
            new DataSourceItem("gh", "Ghana"),
            new DataSourceItem("gi", "Gibraltar"),
            new DataSourceItem("gl", "Greenland"),
            new DataSourceItem("gm", "Gambia"),
            new DataSourceItem("gn", "Guinea"),
            new DataSourceItem("gp", "Guadeloupe"),
            new DataSourceItem("gq", "Equatorial Guinea"),
            new DataSourceItem("gr", "Greece"),
            new DataSourceItem("gt", "Guatemala"),
            new DataSourceItem("gu", "Guam"),
            new DataSourceItem("gy", "Guyana"),
            new DataSourceItem("hk", "Hong Kong"),
            new DataSourceItem("hn", "Honduras"),
            new DataSourceItem("hr", "Croatia"),
            new DataSourceItem("ht", "Haiti"),
            new DataSourceItem("hu", "Hungary"),
            new DataSourceItem("id", "Indonesia"),
            new DataSourceItem("ie", "Ireland"),
            new DataSourceItem("il", "Israel"),
            new DataSourceItem("im", "Isle of Man"),
            new DataSourceItem("in", "India"),
            new DataSourceItem("iq", "Iraq"),
            new DataSourceItem("is", "Iceland"),
            new DataSourceItem("it", "Italy"),
            new DataSourceItem("je", "Jersey"),
            new DataSourceItem("jm", "Jamaica"),
            new DataSourceItem("jo", "Jordan"),
            new DataSourceItem("jp", "Japan"),
            new DataSourceItem("ke", "Kenya"),
            new DataSourceItem("kg", "Kyrgyzstan"),
            new DataSourceItem("kh", "Cambodia"),
            new DataSourceItem("ki", "Kiribati"),
            new DataSourceItem("kn", "Saint Kitts and Nevis"),
            new DataSourceItem("kr", "Korea, Republic of"),
            new DataSourceItem("kw", "Kuwait"),
            new DataSourceItem("ky", "Cayman Islands"),
            new DataSourceItem("kz", "Kazakhstan"),
            new DataSourceItem("la", "Lao People’s Democratic Republic"),
            new DataSourceItem("lb", "Lebanon"),
            new DataSourceItem("lc", "Saint Lucia"),
            new DataSourceItem("li", "Liechtenstein"),
            new DataSourceItem("lk", "Sri Lanka"),
            new DataSourceItem("ls", "Lesotho"),
            new DataSourceItem("lt", "Lithuania"),
            new DataSourceItem("lu", "Luxembourg"),
            new DataSourceItem("lv", "Latvia"),
            new DataSourceItem("ly", "Libya"),
            new DataSourceItem("ma", "Morocco"),
            new DataSourceItem("mc", "Monaco"),
            new DataSourceItem("md", "Moldova"),
            new DataSourceItem("me", "Montenegro"),
            new DataSourceItem("mg", "Madagascar"),
            new DataSourceItem("mk", "North Macedonia"),
            new DataSourceItem("ml", "Mali"),
            new DataSourceItem("mm", "Myanmar"),
            new DataSourceItem("mn", "Mongolia"),
            new DataSourceItem("mq", "Martinique"),
            new DataSourceItem("mr", "Mauritania"),
            new DataSourceItem("ms", "Montserrat"),
            new DataSourceItem("mt", "Malta"),
            new DataSourceItem("mu", "Mauritius"),
            new DataSourceItem("mv", "Maldives"),
            new DataSourceItem("mw", "Malawi"),
            new DataSourceItem("mx", "Mexico"),
            new DataSourceItem("my", "Malaysia"),
            new DataSourceItem("mz", "Mozambique"),
            new DataSourceItem("na", "Namibia"),
            new DataSourceItem("nc", "New Caledonia"),
            new DataSourceItem("ne", "Niger"),
            new DataSourceItem("ng", "Nigeria"),
            new DataSourceItem("ni", "Nicaragua"),
            new DataSourceItem("nl", "Netherlands"),
            new DataSourceItem("no", "Norway"),
            new DataSourceItem("np", "Nepal"),
            new DataSourceItem("nr", "Nauru"),
            new DataSourceItem("nu", "Niue"),
            new DataSourceItem("nz", "New Zealand"),
            new DataSourceItem("om", "Oman"),
            new DataSourceItem("pa", "Panama"),
            new DataSourceItem("pe", "Peru"),
            new DataSourceItem("pf", "French Polynesia"),
            new DataSourceItem("pg", "Papua New Guinea"),
            new DataSourceItem("ph", "Philippines"),
            new DataSourceItem("pk", "Pakistan"),
            new DataSourceItem("pl", "Poland"),
            new DataSourceItem("pn", "Pitcairn"),
            new DataSourceItem("pr", "Puerto Rico"),
            new DataSourceItem("ps", "Palestine, State of"),
            new DataSourceItem("pt", "Portugal"),
            new DataSourceItem("py", "Paraguay"),
            new DataSourceItem("qa", "Qatar"),
            new DataSourceItem("re", "Réunion"),
            new DataSourceItem("ro", "Romania"),
            new DataSourceItem("rs", "Serbia"),
            new DataSourceItem("ru", "Russian Federation"),
            new DataSourceItem("rw", "Rwanda"),
            new DataSourceItem("sa", "Saudi Arabia"),
            new DataSourceItem("sb", "Solomon Islands"),
            new DataSourceItem("sc", "Seychelles"),
            new DataSourceItem("se", "Sweden"),
            new DataSourceItem("sg", "Singapore"),
            new DataSourceItem("sh", "Saint Helena, Ascension and Tristan da Cunha"),
            new DataSourceItem("si", "Slovenia"),
            new DataSourceItem("sk", "Slovakia"),
            new DataSourceItem("sl", "Sierra Leone"),
            new DataSourceItem("sm", "San Marino"),
            new DataSourceItem("sn", "Senegal"),
            new DataSourceItem("so", "Somalia"),
            new DataSourceItem("sr", "Suriname"),
            new DataSourceItem("st", "Sao Tome and Principe"),
            new DataSourceItem("sv", "El Salvador"),
            new DataSourceItem("td", "Chad"),
            new DataSourceItem("tg", "Togo"),
            new DataSourceItem("th", "Thailand"),
            new DataSourceItem("tj", "Tajikistan"),
            new DataSourceItem("tk", "Tokelau"),
            new DataSourceItem("tl", "Timor-Leste"),
            new DataSourceItem("tm", "Turkmenistan"),
            new DataSourceItem("tn", "Tunisia"),
            new DataSourceItem("to", "Tonga"),
            new DataSourceItem("tr", "Turkey"),
            new DataSourceItem("tt", "Trinidad and Tobago"),
            new DataSourceItem("tw", "Taiwan"),
            new DataSourceItem("tz", "Tanzania"),
            new DataSourceItem("ua", "Ukraine"),
            new DataSourceItem("ug", "Uganda"),
            new DataSourceItem("us", "United States"),
            new DataSourceItem("uy", "Uruguay"),
            new DataSourceItem("uz", "Uzbekistan"),
            new DataSourceItem("vc", "Saint Vincent and the Grenadines"),
            new DataSourceItem("ve", "Venezuela"),
            new DataSourceItem("vg", "Virgin Islands, British"),
            new DataSourceItem("vi", "Virgin Islands, U.S."),
            new DataSourceItem("vn", "Viet Nam"),
            new DataSourceItem("vu", "Vanuatu"),
            new DataSourceItem("ws", "Samoa"),
            new DataSourceItem("ye", "Yemen"),
            new DataSourceItem("yt", "Mayotte"),
            new DataSourceItem("za", "South Africa"),
            new DataSourceItem("zm", "Zambia"),
            new DataSourceItem("zw", "Zimbabwe"),
        };
    }
}
